const dirActiveIngredientsSeed = [
    {'ingredients': 'benzoyl peroxide'},
    {'ingredients': 'retinol'},
    {'ingredients': 'bakuchiol'},
    {'ingredients': 'adapalene'},
    {'ingredients': 'salicylic acid(bha)'},
    {'ingredients': 'azelaic acid'},
    {'ingredients': 'alpha hydroxy acids-lactic acid'},
    {'ingredients': 'glycolic acid(aha)'},
    {'ingredients': 'tea tree oil'},
    {'ingredients': 'centella asiatica'},
    {'ingredients': 'vitamin c'},
    {'ingredients': 'kojic acid'},
    {'ingredients': 'retinol'},
    {'ingredients': 'tranexamic acid'},
    {'ingredients': 'niacinamide'},
    {'ingredients': 'mandelic acid'},
    {'ingredients': 'arbutin'},
    {'ingredients': 'alpha-arbutin'},
    {'ingredients': 'licorice root extract'},
    {'ingredients': 'hyaluronnic acid'},
    {'ingredients': 'glycerin'},
    {'ingredients': 'ceramides'},
    {'ingredients': 'squalane'},
    {'ingredients': 'lactic acid'},
    {'ingredients': 'sodium hyaluronate'},
    {'ingredients': 'amino acids'},
    {'ingredients': 'snail mucin'},
    {'ingredients': 'glycolic acid(aha)'},
    {'ingredients': 'peptides'},
    {'ingredients': 'grape seed extract'},
    {'ingredients': 'green tea extract'},
    {'ingredients': 'coenzyme q10'},
    {'ingredients': 'resveratrol'}]

module.exports = dirActiveIngredientsSeed