// const productsSeed = [
//     {
//         productID:'001C',
//         name:'CeraVe Foaming Facial Cleanser',
//         price:200,
//         skinType:['oily'],
//         productType:['cleanser'],
//         sensitive:false
//     },
//     {
//         productID:'002C',
//         name:'Neutrogena Ultra Gentle Daily Cleanser',
//         price:200,
//         skinType:['oily'],
//         productType:['cleanser'],
//         sensitive:false
//     }
// ]

// const json = JSON.stringify(productsSeed)

const productsSeed = [{'productID': 'C001',
'name': 'CeraVe Foaming Facial Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C002',
'name': 'Neutrogena Ultra Gentle Daily Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C003',
'name': 'La Roche-Posay Toleriane Purifying Foaming Cleanser for Oily Skin',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C004',
'name': 'Mario Badescu Enzyme Cleansing Gel',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C005',
'name': 'Olay Cleanse Gentle Foaming Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C006',
'name': 'Neutrogena Oil-Free Salicylic-Acid Acne-Fighting Face Wash',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': ['salicylic acid(bha)'],
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C007',
'name': 'Aveeno Clear Complexion Foaming Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C008',
'name': 'Clean & Clear Acne Triple Clear Facial Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C009',
'name': 'La Roche-Posay Effaclar Deep-Cleansing Foaming-Cream Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C010',
'name': 'Boscia Detoxifying Black Charcoal Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C011',
'name': 'First Aid Beauty Pure Skin Deep Cleanser with Red Clay – Face Wash for Oily or Blemish-Prone Skin',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C012',
'name': 'Atticus Mineral Cleanser',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C013',
'name': 'First Aid Beauty Pure Skin Face Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C014',
'name': 'Kiehl’s Ultra Facial Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C015',
'name': 'Mario Badescu Acne Facial Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C016',
'name': 'Differin Daily Deep Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C017',
'name': 'La Roche-Posay Toleriane Hydrating Gentle Cleanser',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C018',
'name': 'Clinique Liquid Facial Soap, Extra Mild',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C019',
'name': 'Hada Labo Tokyo Gentle Hydrating Cleanser',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C020',
'name': 'Aveeno Absolutely Ageless Nourishing Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C021',
'name': 'CeraVe Hydrating Facial Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['ceramides'],
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C022',
'name': 'EltaMD Foaming Facial Cleanser',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'C023',
'name': 'Bioderma Sébium Global Cover Cleanser',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': ['bakuchiol'],
'productType': 'cleanser',
'sunscreenType': ''},
{'productID': 'T001',
'name': 'Beauty of Joseon Glow Deep Serum : Rice + Alpha Arbutin 30ml',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['alpha arbutin'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T002',
'name': 'Good Molucules tranexemic Acid',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['tranexamic acid '],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T003',
'name': 'Good Molucules Vitamin C powder',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['vitamin c'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T004',
'name': 'Cerave Vitamin C serum',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['vitamin c'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T005',
'name': 'Differin Adapalene gel',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['adapalene'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T006',
'name': 'Cerave Retinol Resurfacing gel',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['retinol'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T007',
'name': 'Naturium AZELAIC TOPICAL ACID 10%',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['azelaic acid',
 'niacinamide',
 'vitamin c',
 'coffee seed extract'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T008',
'name': 'Mandelic Acid 10% + HA',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': ['mandelic acid', 'hylauronic acid '],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'T009',
'name': 'Herbivore Bakuchiol Retinol Alternative Serum',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': ['bakuchiol'],
'productType': 'treatment',
'sunscreenType': ''},
{'productID': 'M001',
'name': 'Hydro Boost Hyaluronic Acid Face Moisturizer',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': ['hyaluronic acid'],
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M002',
'name': 'SkinActive 3-in-1 Face Moisturizer with Green Tea',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': ['green tea'],
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M003',
'name': 'Oil-Free Acne Moisturizer',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M004',
'name': 'Multi Correxion 5-in-1 Daily Moisturizer',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M005',
'name': 'Effaclar Mat Face Moisturizer',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M006',
'name': 'Complexion Rescue Tinted Hydrating Gel Cream SPF 30',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M007',
'name': 'Oil-Free Moisture for Combination Skin',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M008',
'name': 'Cetaphil Moisturizing Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M009',
'name': 'First Aid Beauty Ultra Repair Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M010',
'name': 'Tatcha The Dewy Skin Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M011',
'name': 'Biossance Squalane + Probiotic Gel Moisturizer',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['squalane'],
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M012',
'name': 'CeraVe Moisturising Cream',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M013',
'name': 'Versed Skin Soak Rich Moisture Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M014',
'name': 'Plum Plump Hyaluronic Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['hyaluronic acid'],
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M015',
'name': 'Aveeno Calm + Restore Oat Gel Facial Moisturizer',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M016',
'name': 'First Aid Beauty Ultra Repair Cream Intense Hydration',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'M017',
'name': 'Corsx Snail muchin',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['snail mucin', 'hyaluronic acid'],
'productType': 'moisturiser',
'sunscreenType': ''},
{'productID': 'S001',
'name': 'Bliss Block Star Invisible Daily Sunscreen',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': ['zinc oxide', 'titanium dioxide'],
'productType': 'sunscreen',
'sunscreenType': 'mineral'},
{'productID': 'S002',
'name': 'Supergoop Unseen Sunscreen',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'sunscreen',
'sunscreenType': ''},
{'productID': 'S003',
'name': 'Aveeno Positively Radiant Sheer Daily Moisturizer',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': ['homosalate',
 'octisalate',
 'avobenzone',
 'oxybenzone',
 'octocrylene'],
'productType': 'sunscreen',
'sunscreenType': 'chemical'},
{'productID': 'S004',
'name': 'EltaMD UV Clear Facial Sunscreen SPF 46',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': ['zinc oxide'],
'productType': 'sunscreen',
'sunscreenType': 'mineral'},
{'productID': 'S005',
'name': 'La Roche-Posay Anthelios Ultra Light Sunscreen Fluid',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'sunscreen',
'sunscreenType': ''},
{'productID': 'S006',
'name': 'Olay Daily Moisturizer with SPF 30',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': ['octinoxate',
 'zinc oxide',
 'octocrylene',
 'octisalate'],
'productType': 'sunscreen',
'sunscreenType': ''},
{'productID': 'S007',
'name': 'Fixderma Shadow SPF 50+ Cream',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': ['octinoxate',
 'titanium dioxide',
 'avobenzone',
 'benzophenone-4'],
'productType': 'sunscreen',
'sunscreenType': ''},
{'productID': 'S008',
'name': 'Laneige Watery Sun Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'sunscreen',
'sunscreenType': ''},
{'productID': 'S009',
'name': "Just Herbs Sun'nil Sun Protection Lotion",
'skinType': 'dry,combination',
'sensitive': 'false',
'activeIngredients': ['jojoba oil', 'grape seed', 'zinc oxide'],
'productType': 'sunscreen',
'sunscreenType': ''},
{'productID': 'S010',
'name': "Suntique I'm Aqua Sun Essence",
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['centella asiatica', 'aloe vera'],
'productType': 'sunscreen',
'sunscreenType': ''}]

module.exports = productsSeed