const productsSeed = [{'productID': 'C001',
'name': 'CeraVe Foaming Facial Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '0.9'},
{'productID': 'C002',
'name': 'Neutrogena Ultra Gentle Daily Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '8.2'},
{'productID': 'C003',
'name': 'La Roche-Posay Toleriane Purifying Foaming Cleanser for Oily Skin',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '13.8'},
{'productID': 'C004',
'name': 'Mario Badescu Enzyme Cleansing Gel',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '4.0'},
{'productID': 'C005',
'name': 'Olay Cleanse Gentle Foaming Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '14.9'},
{'productID': 'C006',
'name': 'Neutrogena Oil-Free Salicylic-Acid Acne-Fighting Face Wash',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': ['salicylic acid(bha)'],
'productType': 'cleanser',
'sunscreenType': '',
'price': '7.1'},
{'productID': 'C007',
'name': 'Aveeno Clear Complexion Foaming Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '8.6'},
{'productID': 'C008',
'name': 'Clean & Clear Acne Triple Clear Facial Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '23.5'},
{'productID': 'C009',
'name': 'La Roche-Posay Effaclar Deep-Cleansing Foaming-Cream Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '7.4'},
{'productID': 'C010',
'name': 'Boscia Detoxifying Black Charcoal Cleanser',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '4.5'},
{'productID': 'C011',
'name': 'First Aid Beauty Pure Skin Deep Cleanser with Red Clay – Face Wash for Oily or Blemish-Prone Skin',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '20.9'},
{'productID': 'C012',
'name': 'Atticus Mineral Cleanser',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '10.1'},
{'productID': 'C013',
'name': 'First Aid Beauty Pure Skin Face Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '24.5'},
{'productID': 'C014',
'name': 'Kiehl’s Ultra Facial Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '24.1'},
{'productID': 'C015',
'name': 'Mario Badescu Acne Facial Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '0.7'},
{'productID': 'C016',
'name': 'Differin Daily Deep Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '15.8'},
{'productID': 'C017',
'name': 'La Roche-Posay Toleriane Hydrating Gentle Cleanser',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '10.3'},
{'productID': 'C018',
'name': 'Clinique Liquid Facial Soap, Extra Mild',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '17.4'},
{'productID': 'C019',
'name': 'Hada Labo Tokyo Gentle Hydrating Cleanser',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '17.0'},
{'productID': 'C020',
'name': 'Aveeno Absolutely Ageless Nourishing Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '14.8'},
{'productID': 'C021',
'name': 'CeraVe Hydrating Facial Cleanser',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['ceramides'],
'productType': 'cleanser',
'sunscreenType': '',
'price': '28.0'},
{'productID': 'C022',
'name': 'EltaMD Foaming Facial Cleanser',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'cleanser',
'sunscreenType': '',
'price': '9.4'},
{'productID': 'C023',
'name': 'Bioderma Sébium Global Cover Cleanser',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': ['bakuchiol'],
'productType': 'cleanser',
'sunscreenType': '',
'price': '11.4'},
{'productID': 'T001',
'name': 'Beauty of Joseon Glow Deep Serum : Rice + Alpha Arbutin 30ml',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['alpha arbutin'],
'productType': 'treatment',
'sunscreenType': '',
'price': '10.0'},
{'productID': 'T002',
'name': 'Good Molucules tranexemic Acid',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['tranexamic acid '],
'productType': 'treatment',
'sunscreenType': '',
'price': '17.6'},
{'productID': 'T003',
'name': 'Good Molucules Vitamin C powder',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['vitamin c'],
'productType': 'treatment',
'sunscreenType': '',
'price': '26.6'},
{'productID': 'T004',
'name': 'Cerave Vitamin C serum',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['vitamin c'],
'productType': 'treatment',
'sunscreenType': '',
'price': '17.2'},
{'productID': 'T005',
'name': 'Differin Adapalene gel',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['adapalene'],
'productType': 'treatment',
'sunscreenType': '',
'price': '22.4'},
{'productID': 'T006',
'name': 'Cerave Retinol Resurfacing gel',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['retinol'],
'productType': 'treatment',
'sunscreenType': '',
'price': '24.7'},
{'productID': 'T007',
'name': 'Naturium AZELAIC TOPICAL ACID 10%',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['azelaic acid',
 'niacinamide',
 'vitamin c',
 'coffee seed extract'],
'productType': 'treatment',
'sunscreenType': '',
'price': '18.4'},
{'productID': 'T008',
'name': 'Mandelic Acid 10% + HA',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': ['mandelic acid', 'hylauronic acid '],
'productType': 'treatment',
'sunscreenType': '',
'price': '9.6'},
{'productID': 'T009',
'name': 'Herbivore Bakuchiol Retinol Alternative Serum',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': ['bakuchiol'],
'productType': 'treatment',
'sunscreenType': '',
'price': '11.2'},
{'productID': 'M001',
'name': 'Hydro Boost Hyaluronic Acid Face Moisturizer',
'skinType': 'all',
'sensitive': 'true',
'activeIngredients': ['hyaluronic acid'],
'productType': 'moisturiser',
'sunscreenType': '',
'price': '27.4'},
{'productID': 'M002',
'name': 'SkinActive 3-in-1 Face Moisturizer with Green Tea',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': ['green tea'],
'productType': 'moisturiser',
'sunscreenType': '',
'price': '26.5'},
{'productID': 'M003',
'name': 'Oil-Free Acne Moisturizer',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '24.8'},
{'productID': 'M004',
'name': 'Multi Correxion 5-in-1 Daily Moisturizer',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '22.9'},
{'productID': 'M005',
'name': 'Effaclar Mat Face Moisturizer',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '17.1'},
{'productID': 'M006',
'name': 'Complexion Rescue Tinted Hydrating Gel Cream SPF 30',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '20.8'},
{'productID': 'M007',
'name': 'Oil-Free Moisture for Combination Skin',
'skinType': 'oily',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '22.3'},
{'productID': 'M008',
'name': 'Cetaphil Moisturizing Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '18.8'},
{'productID': 'M009',
'name': 'First Aid Beauty Ultra Repair Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '2.9'},
{'productID': 'M010',
'name': 'Tatcha The Dewy Skin Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '29.1'},
{'productID': 'M011',
'name': 'Biossance Squalane + Probiotic Gel Moisturizer',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['squalane'],
'productType': 'moisturiser',
'sunscreenType': '',
'price': '28.0'},
{'productID': 'M012',
'name': 'CeraVe Moisturising Cream',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '17.4'},
{'productID': 'M013',
'name': 'Versed Skin Soak Rich Moisture Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '10.9'},
{'productID': 'M014',
'name': 'Plum Plump Hyaluronic Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['hyaluronic acid'],
'productType': 'moisturiser',
'sunscreenType': '',
'price': '14.5'},
{'productID': 'M015',
'name': 'Aveeno Calm + Restore Oat Gel Facial Moisturizer',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '29.5'},
{'productID': 'M016',
'name': 'First Aid Beauty Ultra Repair Cream Intense Hydration',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': '',
'productType': 'moisturiser',
'sunscreenType': '',
'price': '7.3'},
{'productID': 'M017',
'name': 'Corsx Snail muchin',
'skinType': 'all',
'sensitive': 'false',
'activeIngredients': ['snail mucin', 'hyaluronic acid'],
'productType': 'moisturiser',
'sunscreenType': '',
'price': '23.3'},
{'productID': 'S001',
'name': 'Bliss Block Star Invisible Daily Sunscreen',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': ['zinc oxide', 'titanium dioxide'],
'productType': 'sunscreen',
'sunscreenType': 'mineral',
'price': '9.9'},
{'productID': 'S002',
'name': 'Supergoop Unseen Sunscreen',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'sunscreen',
'sunscreenType': '',
'price': '22.9'},
{'productID': 'S003',
'name': 'Aveeno Positively Radiant Sheer Daily Moisturizer',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': ['homosalate',
 'octisalate',
 'avobenzone',
 'oxybenzone',
 'octocrylene'],
'productType': 'sunscreen',
'sunscreenType': 'chemical',
'price': '1.4'},
{'productID': 'S004',
'name': 'EltaMD UV Clear Facial Sunscreen SPF 46',
'skinType': 'oily ',
'sensitive': 'true',
'activeIngredients': ['zinc oxide'],
'productType': 'sunscreen',
'sunscreenType': 'mineral',
'price': '14.0'},
{'productID': 'S005',
'name': 'La Roche-Posay Anthelios Ultra Light Sunscreen Fluid',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'sunscreen',
'sunscreenType': '',
'price': '26.3'},
{'productID': 'S006',
'name': 'Olay Daily Moisturizer with SPF 30',
'skinType': 'oily ',
'sensitive': 'false',
'activeIngredients': ['octinoxate',
 'zinc oxide',
 'octocrylene',
 'octisalate'],
'productType': 'sunscreen',
'sunscreenType': '',
'price': '29.3'},
{'productID': 'S007',
'name': 'Fixderma Shadow SPF 50+ Cream',
'skinType': 'dry',
'sensitive': 'true',
'activeIngredients': ['octinoxate',
 'titanium dioxide',
 'avobenzone',
 'benzophenone-4'],
'productType': 'sunscreen',
'sunscreenType': '',
'price': '6.7'},
{'productID': 'S008',
'name': 'Laneige Watery Sun Cream',
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': '',
'productType': 'sunscreen',
'sunscreenType': '',
'price': '25.0'},
{'productID': 'S009',
'name': "Just Herbs Sun'nil Sun Protection Lotion",
'skinType': 'dry,combination',
'sensitive': 'false',
'activeIngredients': ['jojoba oil', 'grape seed', 'zinc oxide'],
'productType': 'sunscreen',
'sunscreenType': '',
'price': '24.2'},
{'productID': 'S010',
'name': "Suntique I'm Aqua Sun Essence",
'skinType': 'dry',
'sensitive': 'false',
'activeIngredients': ['centella asiatica', 'aloe vera'],
'productType': 'sunscreen',
'sunscreenType': '',
'price': '25.2'}]

module.exports = productsSeed