const seedUsers = [
    {
        userName:"guest",
        email:"guest",
        password:"guest",
    },
    {
        userName:"admin",
        email:"admin",
        password:"admin",
        isAdmin:"true"
    },
    {
        userName:"superadmin",
        email:"superadmin",
        password:"superadmin",
        isAdmin:"true",
        isSuperAdmin:'true'
    },
    {
        userName:"penguin1",
        email:"penguin1@example.com",
        password:"iamapenguin",
        skinType:"oily",
        skinSensitivity:true,
        skinGoal:'target hyper-pigmentation'
    },
    {
        userName:"penguin2",
        email:"penguin2@example.com",
        password:"iamapenguin",
        skinType:"combination",
        skinSensitivity:false,
        skinGoal:'hydration'
    },
    {
        userName:"penguin3",
        email:"penguin3@example.com",
        password:"iamapenguin",
        skinType:"dry",
        skinSensitivity:true,
        skinGoal:'anti-aging'
    },
    {
        userName:"penguin4",
        email:"penguin4@example.com",
        password:"iamapenguin",
        skinSensitivity:true,
    },
    {
        userName:"a",
        email:"a",
        password:"a",
        isAdmin:"true"
    },
    {
        userName:"b",
        email:"b",
        password:"b",
        skinType:"dry",
        skinSensitivity:true,
        skinGoal:'anti-aging'
    },
    {
        userName:"c",
        email:"c",
        password:"c",
        skinType:"dry",
        skinSensitivity:true
    },
]

module.exports = seedUsers